### ISSUE TITLE
Fan control

### ISSUE THREAD

**Issue by wjketting** [peternijssen/spiderpy#3]
When will the fan option be available?
I'm running Home Assistant as Hassio install.
Is it possible to do a custom install to test in meanwhile?

**Comment by peternijssen** [comment]
Thanks for your report. I will try to integrate it within HA. Problem is only that I don't have a fan myself that works with Spider, so I cannot guarantee from the start that it will work perfectly.

Will work on it this weekend and see what I can do.

**Comment by peternijssen** [comment]
Could you try the following?

Place the following code in "custom_components/spider.py":
https://gist.github.com/peternijssen/32079cddec03c90149509a51169a7e3d

Place the following code in "custom_components/climate/spider.py":
https://gist.github.com/peternijssen/6adbc57375b2c2fb5bd1470809b149d5

You can enable additional debugging in HA:
```
logger:
  default: error
  logs:
    custom_components.spider: debug
    custom_components.climate.spider: debug
```

You should now be able to control the fan speed. Let me know if it worked or not, so I can make it formal part of HA.

Thanks!
