### ISSUE TITLE
Opties in automation

### ISSUE THREAD

**Issue by trouble2** [peternijssen/spiderpy#85]
Hi, als ik in HA een automation wil aanmaken, dan kan ik alleen kiezen voor:
Wijzig de HVAC-modus op spIDer zone 
En dan kan ik kiezen voor Heat of Cool.

Ik weet niet of het mogelijk is, maar ik zou graag de fan speed bv. kunnen wijzigen 
Of evt. een bepaalde temperatuur instellen.

**Comment by peternijssen** [comment]
Hi @trouble2. Dat kan gewoon met de standaard functies van HA als het goed is. Althans, met YAML, ik weet niet of de automation editor dat ook kan (ik zou zeggen van wel eigenlijk 🤔)

Ik pas bijvoorbeeld de temperatuur bijvoorbeeld zo aan:
```yaml
    - service: climate.set_temperature
      target:
        entity_id: climate.woonkamer
      data:
        temperature: 16
```
